spring.application.name=JDevERP-PRO


#==========Conexao com banco de dados=========
spring.datasource.url=jdbc:postgresql://localhost:5432/jdev-erp-pro?reWriteBatchedInserts=true&autoreconnect=true
spring.datasource.username=postgres
spring.datasource.password=admin1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.platform=postgres
spring.datasource.dbcp2.pool-prepared-statements=true
spring.datasource.dbcp2.max-open-prepared-statements=450

#==========Spring Data JPA=========
spring.jpa.hibernate.ddl-auto=update


#==========Contexto do projeto=============
server.servlet.context-path=/jdev-erp-pro-back-end-dev

#==========Spring Security=================
spring.security.user.name=admin
spring.security.user.password=admin